### ISSUE TITLE
Syntax error on Node 10 (?? null coalescing operator)

### ISSUE THREAD

**Issue by stephenwf** [gajus/slonik-sql-tag-raw#11]
Getting the same error as the [Travis run](https://travis-ci.com/github/gajus/slonik-sql-tag-raw/jobs/474119379)
```
/home/node/app/node_modules/slonik-sql-tag-raw/dist/utilities/interpolatePositionalParameterReferences.js:9
     const bindingNames = (inputSql.match(/\$(\d+)/g) ?? [])
                                                       ^
 SyntaxError: Unexpected token '?'
     at wrapSafe (internal/modules/cjs/loader.js:915:16)
     at Module._compile (internal/modules/cjs/loader.js:963:27)
```

I think the target of `esnext` in `tsconfig.json` will not support node 10, maybe targeting es6 would fix resolve the issue?

**Comment by gajus** [comment]
I think it is time to drop v10 regardless. Active support for v10 ended long time ago. Official support is ending in 2 months.

https://nodejs.org/en/about/releases/

**Comment by stephenwf** [comment]
That's fair! Did a quick check on MDN for the syntax, looks like Node 14 and above (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#browser_compatibility). 

Happy to raise a PR, can switch the tests out to Node 12

**Comment by gajus** [comment]
Since this was an accidental breaking change, for now we should just change `tsconfig.json` to make it compatible with Node.js 10. Afterwards, we can make a breaking change.

**Comment by MatthewHerbst** [comment]
@gajus is that a change you can make, or would you like a PR submitted? Unfortunately this is breaking tests for us when trying to update from v1.0.2 -> v1.1.0 since we run on Node 12 (because AWS still doesn't support Node 14 on EBS... 😢 )
