### ISSUE TITLE
Missing typescript types

### ISSUE THREAD

**Issue by thomasthiebaud** [gajus/slonik-sql-tag-raw#9]
Hej,

There is no typescript types exported for that module. Since [slonik](https://github.com/gajus/slonik) has typescript support I though I should ask here if there is any plan to add typescript definitions

**Comment by ademilsonfp** [comment]
I need these type definitions too, currently I'm using a shim declaration in my TS project, but not sure if it's proper:

```ts
declare module 'slonik-sql-tag-raw' {
  import {
    ValueExpressionType,
    SqlTokenType
  } from 'slonik';

  function raw(
    sql: string,
    values?: ReadonlyArray<ValueExpressionType>
  ): SqlTokenType
}
```

**Comment by gajus** [comment]
I would accept a PR that rewrites this library to TS.

**Comment by thomasthiebaud** [comment]
I'll try to have a look at it next week, unless someone else can do it faster

**Comment by ademilsonfp** [comment]
[PR](https://github.com/gajus/slonik-sql-tag-raw/pull/10) done.

**Comment by gajus** [comment]
Thank you
